services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Mount the current directory inside the container
      - /usr/src/app/node_modules  # Exclude node_modules from being overwritten
    environment:
      - WATCHPACK_POLLING=true  # Use polling for file changes  
    command: npm start  # Use the development server to enable hot reloading
